cancervariants/variation-normalization

frontend/src/components/TokenTable.tsx, frontend/src/types/VarlexTypes.ts, varlexapp/models/token.py, varlexapp/schemas/token_schema.py, varlexapp/tokenizers/basic_regex_tokenizer.py, varlexapp/tokenizers/gene_pair.py, varlexapp/tokenizers/gene_symbol.py, varlexapp/tokenizers/tokenize.py
ex for a search term of ENSG00000157764 return BRAF and the original id
=> Include both the matched token and the original string

.gitignore, .travis.yml, README.md, environment.yml, requirements.txt, tests/tokenizers/test_fusion.py, tests/tokenizers/tokenizer_base.py
Don't run no-op tests in the base module, update readme, and get rid of `pass`.
closes #9
=> Switch to pytest

main.py, tests/fixtures/translators.yml, tests/fixtures/validators.yml, variant/validators/polypeptide_sequence_variant_base.py
=> Remove duplicates

README.md, tests/test_normalize.py, variant/__init__.py, variant/normalize.py, variant/schemas/ga4gh_vod.py, variant/schemas/normalize_response_schema.py
=> Fix normalize endpoint response

variant/__init__.py, variant/normalize.py
=> Make changes for gene-normalizer

variant/__init__.py, variant/tokenizers/caches/amino_acid_cache.py
=> Support conversion from ter --> *

tests/test_normalize.py, variant/__init__.py, variant/main.py, variant/schemas/__init__.py, variant/schemas/normalize_response_schema.py, variant/schemas/translation_response_schema.py
=> Add service_meta

.gitignore, README.md, variant/__init__.py
=> Download gene symbol files in app init

tests/test_normalize.py, variant/__init__.py, variant/normalize.py
=> Fix label in variation descriptor

setup.py, tests/test_normalize.py, variant/__init__.py, variant/data_sources/transcript_mappings.py, variant/validators/genomic_base.py
=> Error fixes

Pipfile, requirements-dev.txt, requirements.txt, tests/test_normalize.py, tests/translators/translator_base.py, variation/normalize.py, variation/schemas/ga4gh_vrs.py, variation/schemas/ga4gh_vrsatile.py, variation/schemas/normalize_response_schema.py, variation/schemas/to_vrs_response_schema.py
=> Issue 126 vrsatile

README.md
I _think_ this covers the main components of the service. Let me know if I'm missing something
=> Add documentation covering the main parts of the service

variation/to_vrsatile.py, variation/validators/polypeptide_sequence_variation_base.py
Fixed some minor logic due to code rearrangement, and put a comment on reference genome build.
=> Issue 203 query fix

.ebextensions/01_download_data.config, Pipfile, requirements-dev.txt, requirements.txt, setup.cfg
=> Issue 226: psycopg2-binary + postgresql-devel

variation/data_sources/uta.py
Resolves https://github.com/cancervariants/metakb/issues/153
A few ways to handle this (I chose 2)
1) Pin pandas to <8.0
2) Use a sqlalchemy engine connection for the read_sql call
3) Pull pandas out and use something a bit lighter and quicker like numpy arrays or hash tables to do lookups 
I'd wager that this may pop up in uta-tools as well (and this part of the normalizer will get replaced by uta-tools eventually in #171)
=> Use slqalchemy engine for pandas read_sql call

tests/translators/translator_base.py, tests/validators/validator_base.py, variation/__init__.py, variation/hgvs_dup_del_mode.py, variation/mane_transcript.py, variation/query.py, variation/schemas/app_schemas.py, variation/schemas/schemas.py, variation/to_vrs.py, variation/validators/amino_acid_deletion.py, variation/validators/amino_acid_delins.py, variation/validators/amino_acid_insertion.py, variation/validators/coding_dna_deletion.py, variation/validators/coding_dna_delins.py, variation/validators/coding_dna_silent_mutation.py, variation/validators/coding_dna_substitution.py, variation/validators/delins_base.py, variation/validators/duplication_deletion_base.py, variation/validators/genomic_deletion.py, variation/validators/genomic_deletion_range.py, variation/validators/genomic_delins.py, variation/validators/genomic_duplication.py, variation/validators/genomic_silent_mutation.py, variation/validators/genomic_substitution.py, variation/validators/genomic_uncertain_deletion.py, variation/validators/insertion_base.py, variation/validators/polypeptide_sequence_variation_base.py, variation/validators/single_nucleotide_variation_base.py, variation/validators/validate.py, variation/validators/validator.py
- normalize_endpoint --> endpoint_name (validators)
- normalize_endpoint --> try_longest_compatible (mane transcript) 
I believe this will help with code-reuse in #251
=> Use better variable names

.ebextensions/01_download_data.config
=> Issue 266: Fix EB permissions

.github/workflows/close_issue.yml
Did this in VAI. Going to do in our other repos
=> ci: add action for closing issue when merged into staging

tests/test_gnomad_vcf_to_protein.py, variation/query.py
=> fix: gnomad_vcf_to_protein getting ref/alt values

README.md
Helps address #115 
Let me know if there's anything else that should be added
=> docs: update readme for setting up backend services

tests/test_gnomad_vcf_to_protein.py, tests/test_hgvs_dup_del_mode.py, tests/test_hgvs_to_copy_number.py, tests/test_normalize.py, tests/test_parsed_to_abs_cnv.py, tests/test_to_canonical_variation.py, variation/gnomad_vcf_to_protein_variation.py, variation/main.py, variation/normalize.py, variation/schemas/service_schema.py, variation/to_canonical_variation.py, variation/to_copy_number_variation.py, variation/to_vrs.py
=> refactor!: main query methods return pydantic service class response

Pipfile, requirements-dev.txt, requirements.txt, setup.cfg, tests/conftest.py, variation/__init__.py, variation/version.py
Addresses `staging` branch for #336. I also removed the Elastic Beanstalk environment variables and added them to our template.
=> build: update gene-normalizer version to v0.2.6 (staging)

Pipfile, requirements-dev.txt, requirements.txt, setup.cfg
Addresses main branch for #349
=> build: unpin ga4gh.vrs + bump gene-normalizer (main)

Pipfile, requirements-dev.txt, requirements.txt, setup.cfg, variation/version.py
=> build: update dependency versions

tests/test_gnomad_vcf_to_protein.py, variation/gnomad_vcf_to_protein_variation.py, variation/main.py
=> perf: gnomad_vcf_to_protein replace call to uta db with df lookup (staging)

Pipfile, requirements-dev.txt, requirements.txt, setup.cfg
removed unused dev deps + udpate versions for cool-seq-tool / gene-normalizer
=> build: update dependencies

Pipfile, requirements-dev.txt, requirements.txt, setup.cfg
remove unused dev deps + update versions for cool-seq-tool / gene-normalizer
=> build: update dependencies (staging)

Pipfile, requirements-dev.txt, requirements.txt, setup.cfg, tests/test_normalize.py, variation/validators/validator.py
=> fix: TypeError in _is_grch38_assembly (stgaging)

tests/test_gnomad_vcf_to_protein.py, variation/gnomad_vcf_to_protein_variation.py
Close #355 
Notes:
- Cherry picked [this](https://github.com/cancervariants/variation-normalization/commit/8d39a67c00fab349c8f7428c5fb8bc6e69fec79b) commit
=> fix: remove duplicate warnings in gnomad_vcf_to_protein (staging)

tests/fixtures/tokenizers.yml, tests/fixtures/translators.yml, tests/test_normalize.py, variation/tokenizers/caches/nucleotide_cache.py
Address #383 for staging branch
=> fix: add support for ambiguous N IUPAC code for cDNA + genomic (staging)

tests/fixtures/tokenizers.yml, tests/fixtures/translators.yml, tests/test_normalize.py, variation/tokenizers/caches/nucleotide_cache.py
=> fix: add support for ambiguous N IUPAC code for cDNA + genomic

variation/query.py
Address #368 for `main` branch
=> refactor: Allow option to use existing gene-normalizer instance

variation/query.py
=> refactor: Allow option to use existing gene-normalizer instance (staging)

tests/to_copy_number_variation/test_hgvs_to_copy_number.py, variation/validators/genomic_duplication.py
=> fix: catch errors for (#_#)_#dup and #_(#_#)dup HGVS exprs (#419)

.ebextensions/01_download_data.config
- Update python version to 3.11
- Fix unzipping seqrepo
=> chore: update elastic beanstalk commands

codebuild/deploy_eb_env.py, codebuild/deploy_eb_env_dev.py
=> cicd: update sc_product_id

.pre-commit-config.yaml
@jsstevenson is this what you were thinking for pre-commit config?
=> chore: have black run before ruff + have it autofix

tests/conftest.py, tests/test_normalize.py
=> refactor: rm lingering structural_type

.ebextensions/01_download_data.config
Will still need to do #509 , but this updates the elastic beanstalk commands
=> cicd: update elastic beanstalk eb extensions for python3.11 + p7zip

Pipfile, setup.cfg, tests/conftest.py, variation/gnomad_vcf_to_protein_variation.py, variation/hgvs_dup_del_mode.py, variation/normalize.py, variation/query.py, variation/schemas/token_response_schema.py, variation/schemas/translation_response_schema.py, variation/to_copy_number_variation.py, variation/to_vrs.py, variation/tokenizers/gene_symbol.py, variation/translate.py, variation/translators/amplification.py, variation/translators/translator.py, variation/utils.py, variation/validate.py, variation/validators/genomic_base.py, variation/validators/validator.py, variation/vrs_representation.py
Addresses #408 for `staging` branch
* Updates pydantic (v2), ga4gh.vrs, gene-normalizer, + cool-seq-tool versions
* Import statements for cool-seq-tool updated to latest architecture changes
* gene descriptor --> gene for gene-normalizer
* Updates VrsSeqLocAcStatus with cool-seq-tool enum updates
=> build!: update depdency versions

variation/query.py
close #518 
Manually tested. Created #519
=> fix: vrs-python translator import statement

pyproject.toml
No meaningful changes -- this just restructures and changes some metadata configs to be consistent across projects
=> build: reorganize build metadata

README.md
This repo is a little bit irregular compared to our other projects, so I don't think it needs to adhere to the exact structure we've used elsewhere. I did add in a few things, though, until a complete docs instance is running.
=> docs: readme glow-up

.github/workflows/stale.yaml
Resolves `invalid value workflow reference: no version specified`
=> fix(cicd): add reference to stalebot

src/variation/gnomad_vcf_to_protein_variation.py, src/variation/normalize.py, src/variation/schemas/copy_number_schema.py, src/variation/schemas/hgvs_to_copy_number_schema.py, src/variation/schemas/service_schema.py, src/variation/to_copy_number_variation.py, src/variation/to_vrs.py
ugh didn't wait for checks to pass
=> style: ruff format

Pipfile, pyproject.toml, src/variation/main.py, tests/test_normalize.py
=> fix: update ga4gh.vrs + add back response_model configs for FastAPI

.github/workflows/branch-warning.yaml
=> cicd: check if PR to main is coming from staging

.gitignore, README.md
This PR merges commits from `main` back to `dev` if they weren't there already (stop me if any of this was intentional)
=> chore: bring back commits on `main` to `staging`

pyproject.toml
=> chore!: rename optional dependency

.github/workflows/checks.yaml, pyproject.toml, src/variation/gnomad_vcf_to_protein_variation.py, src/variation/main.py, src/variation/normalize.py, src/variation/to_copy_number_variation.py, src/variation/to_vrs.py
I am hoping this is the last PR before making a new release
=> build!: require python >= 3.11

Pipfile
* Forgot to do this in #582, so Elastic Beanstalk build was failing
=> fix(build): update dependency versions in Pipfile

pyproject.toml, src/variation/hgvs_dup_del_mode.py, src/variation/main.py, src/variation/schemas/service_schema.py, src/variation/translators/genomic_del_dup_base.py, src/variation/translators/genomic_delins.py, src/variation/translators/genomic_insertion.py, src/variation/translators/genomic_reference_agree.py, src/variation/translators/genomic_substitution.py, src/variation/translators/translator.py, src/variation/utils.py, src/variation/validators/validator.py, src/variation/vrs_representation.py
=> build: pin cool-seq-tool version ~=0.9.1

.github/workflows/checks.yaml, Pipfile, pyproject.toml
* also uses ubuntu-22.04 runner for deps gh action job
=> build: pin gene-normalizer version to >=0.7.0

pyproject.toml, tests/conftest.py
* cool-seq-tool version bump: `mane_genes` extension will now include `status`
* pin gene-normalizer
=> build: update cool-seq-tool + pin gene-normalizer

Pipfile, pyproject.toml, src/variation/to_copy_number_variation.py, src/variation/tokenizers/gene_symbol.py, src/variation/translators/amplification.py, tests/conftest.py, tests/test_gnomad_vcf_to_protein.py
* `gene_context.label` -> `gene_context.name` in /gnomad_vcf_to_protein (`label` -> `name` in `MappableConcept`)
=> build!: update ga4gh.vrs

.ebextensions/01_download_data.config, README.md
=> chore: update seqrepo version to 2024-12-20

README.md
=> docs: update uta version to 20241220

README.md, docker-compose.yaml, uta-setup.sql
* Adds option for installing UTA via Docker
=> chore: update developer installation for uta

Pipfile, pyproject.toml
* Default `UTA_DB_URL` is now `postgresql://uta_admin@localhost:5432/uta/uta_20241220`
=> build!: update cool-seq-tool version

Pipfile, pyproject.toml
I'm working on MetaKB and ran into dependency conflicts
=> build: bump cool-seq-tool version
