cancervariants/variation-normalization

tests/fixtures/tokenizers.yml, tests/tokenizers/test_fusion.py, tests/tokenizers/tokenizer_test.py
This sets up a test harness so that we can supply as many test cases for the various tokenizers as we'd like via a yaml file. (Note that this does not actually include any additional tests, merely the scaffolding). 
Classifiers will use the same approach. Closes #4
=> test harness for yaml fixtures

frontend/src/components/SwaggerDocs.tsx, frontend/src/components/TokenTable.tsx, frontend/src/services/VarlexApi.ts, frontend/src/types/VarlexTypes.ts, varlexapp/models/__init__.py, varlexapp/models/token.py, varlexapp/models/token_match_type.py, varlexapp/schemas/token_schema.py, varlexapp/tokenizers/caches/gene_symbol_cache.py, varlexapp/tokenizers/gene_pair.py, varlexapp/tokenizers/gene_symbol.py
This adds the idea of a "match type" to tokens (name, alias, id, etc) with various types of gene matches as the first test. 
This also allows the gene tokenizer to match on previous symbols, aliases, ids, etc, but we will likely want to discuss the specifics of the implementation.
=> Initial support for matching gene aliases, ids, etc

varlexapp/tokenizers/caches/gene_symbol_cache.py, varlexapp/tokenizers/tokenize.py
For gene identifiers (hgnc, entrez, ensembl, etc), use a curie style notation to differentiate which id type to look up.
Along with last week's PR, this closes #2
=> Use CURIE notation for gene ids

tests/classifiers/classifier_base.py, tests/classifiers/test_fusion.py, tests/fixtures/classifiers.yml, tests/fixtures/tokenizers.yml, tests/tokenizers/test_gene.py, tests/tokenizers/test_gene_pair.py, varlexapp/models/classification_type.py, varlexapp/models/confidence_rating.py
This allows us to test both that the string is classified correctly and with the confidence level we expect.
Right now it loads the gene cache per set of tests which makes it slower than it should be. We should optimize that out in a future PR.
=> Initial harness for classification testing

frontend/.env, frontend/.env.development, frontend/src/components/SwaggerDocs.tsx, frontend/src/services/Config.ts, frontend/src/services/VarlexApi.ts
For now this lets us not have to toggle back and forth between domains
in dev vs prod, and will come in handy later as the application grows as
well.
=> Inject config from .env files at build time

variation/mane_transcript.py, variation/validators/validator.py
A few notes
- in cProfile this reduces the startup time for QueryHandler by 40ish seconds (from 55 to 15 roughly)
- A couple of my tests aren't passing in staging or main and are also not passing on this branch so I didn't want to get too fancy, but you could also trim a couple more seconds off by sharing the HGVS Parser object between the MANE transcript class and the Validator classes
- I might have skimmed too quickly but I didn't see where `hgvs_parser` was actually being used, but maybe more focused tests at wherever that is would be appropriate?
=> Share hgvs_parser as class variable

codebuild/deploy_eb_env_dev.py, tests/test_gnomad_vcf_to_protein.py, tests/test_hgvs_dup_del_mode.py, tests/test_hgvs_to_copy_number.py, tests/test_normalize.py, tests/test_parsed_to_abs_cnv.py, tests/test_to_canonical_variation.py, variation/gnomad_vcf_to_protein_variation.py, variation/main.py, variation/normalize.py, variation/schemas/hgvs_to_copy_number_schema.py, variation/schemas/normalize_response_schema.py, variation/schemas/service_schema.py, variation/schemas/to_vrs_response_schema.py, variation/to_canonical_variation.py, variation/to_copy_number_variation.py, variation/to_vrs.py, variation/utils.py
Closes #315 
Notes:
- Add untranslatable_returns_text param to determine if returning VRS Text or None/Empty list
- Remove response_model_exclude_none parameter to allow None in the response
- Temporarily changes dev deployment to terminate after 30 days (will change back to 12 hours once prod is updated with changes in staging)
=> refactor: service response

Pipfile, docs/hgvs_dup_del_mode.md, requirements-dev.txt, requirements.txt, setup.cfg, tests/conftest.py, tests/test_hgvs_dup_del_mode.py, tests/test_to_canonical_variation.py, tests/to_copy_number_variation/test_amplification_to_rel_cnv.py, tests/to_copy_number_variation/test_hgvs_to_copy_number.py, variation/hgvs_dup_del_mode.py, variation/schemas/hgvs_to_copy_number_schema.py, variation/schemas/normalize_response_schema.py, variation/schemas/service_schema.py, variation/to_canonical_variation.py, variation/to_copy_number_variation.py, variation/validators/amplification.py, variation/version.py
Close #344
- Default hgvs dup del mode if relative_copy_class not provided, uses `EFO:0030067` (copy number loss) if deletion or `EFO:0030070` (copy number gain) if duplication
- For tests:
- (If using default characteristics, use above IDs)
`complete loss` → `EFO:0030069`
`partial loss` →  `EFO:0030068`
`copy neutral` → `EFO:0030067`
`low-level gain` → `EFO:0030071`
`high-level gain` → `EFO:0030072`
- I guess the prefix for `CanonicalVariation` also changed: `CLV` --> `CAN`
=> change: relative_copy_class uses EFO IDs

codebuild/deploy_eb_env_dev.py
close #318 
Kyle is no longer using our dev instance since they are running it in their cloud. So we can revert the termination time for dev back to 12
=> cicd: revert dev termination time back to 12 hours

tests/to_copy_number_variation/test_parsed_to_cn_var.py, variation/to_copy_number_variation.py
Words are hard
Notes:
- "assembly is not current supported" --> "assembly is not currently supported"
=> refactor: parsed_to_cn_var warning message

tests/to_copy_number_variation/test_hgvs_to_copy_number.py, variation/validators/genomic_duplication.py, variation/version.py
Address #417 for metaschema branch 
This is a temporary fix. Eventually we will want to add support for these kinds of queries. I will make new issues now
=> fix: catch errors for (#_#)_#dup and #_(#_#)dup HGVS exprs

README.md
Address #401 for metaschema branch . Won't open until #394 is complete
It feels weird that the metaschema version (0.7.X) for variation-normalizer is lower than the 1.3 VRS branch (0.8.X). I'm wondering if for the 1.3 changes, if we should stick with the current 0.5.X? Will make this comment in #394
=> docs: document branch / version tracking

tests/to_copy_number_variation/test_parsed_to_copy_number.py, variation/schemas/copy_number_schema.py, variation/to_copy_number_variation.py
Addresses #443  for metaschema branch. Needed for manuscript analysis
- Provides descriptions for Parsed to CN query classes
- `total_copies` renamed to `copies0`
=> fix: Copy Number Count copies should be Number or Indef/Def Range

tests/test_hgvs_dup_del_mode.py, variation/translators/ambiguous_translator_base.py, variation/translators/genomic_del_dup_base.py
Was not looking at outer coords, but now we are. The long `vrs_ref_allele_seq` will be addressed in #481
=> fix: default mode for hgvs dup del mode wrt rse

tests/test_normalize.py, variation/main.py, variation/normalize.py, variation/validate.py, variation/validators/amplification.py, variation/validators/cdna_deletion.py, variation/validators/cdna_delins.py, variation/validators/cdna_insertion.py, variation/validators/cdna_reference_agree.py, variation/validators/cdna_substitution.py, variation/validators/genomic_base.py, variation/validators/genomic_deletion.py, variation/validators/genomic_deletion_ambiguous.py, variation/validators/genomic_delins.py, variation/validators/genomic_duplication.py, variation/validators/genomic_duplication_ambiguous.py, variation/validators/genomic_insertion.py, variation/validators/genomic_reference_agree.py, variation/validators/genomic_substitution.py, variation/validators/protein_deletion.py, variation/validators/protein_delins.py, variation/validators/protein_insertion.py, variation/validators/protein_reference_agree.py, variation/validators/protein_stop_gain.py, variation/validators/protein_substitution.py, variation/validators/validator.py
=> fix: add `input_assembly` param for gnomad vcf / genomic free text queries

variation/to_vrs.py
Close #500
Forgot to catch the case where there are no valid results. Fixes so that translations is defined
=> fix: add condition when there are no valid results in /to_vrs

variation/normalize.py
Close #502
- Was using `translations` when it should have been using `preferred_translations`
=> fix: _get_priority_translation_result using wrong variable

tests/test_normalize.py, variation/normalize.py, variation/schemas/translation_response_schema.py, variation/translators/genomic_del_dup_base.py, variation/translators/genomic_delins.py, variation/translators/genomic_insertion.py, variation/translators/genomic_reference_agree.py, variation/translators/genomic_substitution.py, variation/translators/translator.py
close #505
Create temp enum, this will be fixed in cool-seq-tool + fix move sorting for preferred translation result
=> fix: still return a result for protein/cdna with no mane data found

tests/conftest.py, tests/fixtures/translators.yml, tests/test_hgvs_dup_del_mode.py, tests/to_copy_number_variation/test_hgvs_to_copy_number.py, tests/to_copy_number_variation/test_parsed_to_copy_number.py, variation/to_copy_number_variation.py, variation/translators/ambiguous_translator_base.py, variation/version.py
close #524 
standard residue -> inter-residue conversion:
(a_b)_(c_d) -> start: models.Range([a-1, b-1]), end: models.Range([c,d])
=> fix: hgvs/free text dup/del end positions for definite ranges

Pipfile, pyproject.toml, src/variation/version.py
There were breaking changes in new versions. The API does not show all fields in VRS Variation.
=> build: pin ga4gh.vrs dependency

tests/conftest.py, tests/fixtures/translators.yml, tests/test_gnomad_vcf_to_protein.py, tests/test_hgvs_dup_del_mode.py, tests/test_normalize.py, tests/test_translator.py, tests/to_copy_number_variation/test_amplification_to_cx_var.py, tests/to_copy_number_variation/test_hgvs_to_copy_number.py, tests/to_copy_number_variation/test_parsed_to_copy_number.py
close #320
* We do not need to be checking VRS IDs on every single test. This reduces to making this check in one place where ga4gh_identify function is called
=> test: only check vrs ids on certain tests

src/variation/hgvs_dup_del_mode.py, src/variation/translators/genomic_del_dup_base.py, src/variation/translators/genomic_delins.py, src/variation/translators/genomic_insertion.py, src/variation/translators/genomic_reference_agree.py, src/variation/translators/genomic_substitution.py, src/variation/translators/translator.py, src/variation/vrs_representation.py, tests/conftest.py, tests/test_hgvs_dup_del_mode.py, tests/test_normalize.py
=> feat: return MANE gene(s) in normalize endpoint for genomic queries

.gitignore
I think this file was leftover from when we took over the repo from WUSTL. This replaces it with the standard GitHub-provided Python ignore, plus our own configurations.
=> chore: use base gitignore

pyproject.toml, src/variation/gnomad_vcf_to_protein_variation.py, src/variation/hgvs_dup_del_mode.py, src/variation/schemas/copy_number_schema.py, src/variation/schemas/gnomad_vcf_to_protein_schema.py, src/variation/schemas/hgvs_to_copy_number_schema.py, src/variation/schemas/token_response_schema.py, src/variation/to_copy_number_variation.py, src/variation/translators/amplification.py, src/variation/translators/translator.py, src/variation/utils.py, src/variation/vrs_representation.py, tests/conftest.py, tests/fixtures/translators.yml, tests/test_hgvs_dup_del_mode.py, tests/test_normalize.py, tests/to_copy_number_variation/test_amplification_to_cx_var.py, tests/to_copy_number_variation/test_hgvs_to_copy_number.py, tests/to_copy_number_variation/test_parsed_to_copy_number.py
close #581 
* Update modules to vrs [2.0.0-ballot.2024-11.3](https://github.com/ga4gh/vrs/tree/2.0.0-ballot.2024-11.3) tag
* `CopyNumberChange` has `mappings` for EFO code
=> feat!: update models to vrs 2.0.0 community review ballot

Pipfile, README.md, pyproject.toml, src/variation/hgvs_dup_del_mode.py, src/variation/schemas/copy_number_schema.py, src/variation/schemas/hgvs_to_copy_number_schema.py, src/variation/to_copy_number_variation.py, src/variation/translators/amplification.py, src/variation/utils.py, tests/conftest.py, tests/fixtures/translators.yml, tests/test_hgvs_dup_del_mode.py, tests/to_copy_number_variation/test_amplification_to_cx_var.py, tests/to_copy_number_variation/test_hgvs_to_copy_number.py, tests/to_copy_number_variation/test_parsed_to_copy_number.py
close #607
* Update ga4gh.vrs + gene normalizer versions to leverage vrs 2.0.1 models
@Mrinal-Thomas-Epic @kattaylor511 This is the update we need to get VRS 2.0.1 IDs
=> feat!: update to vrs 2.0.1 models
